services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Padam87\MoneyBundle\Doctrine\Mapping\Driver\MoneyEmbeddedDriver:
        arguments:
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Doctrine\Mapping\Driver\CurrencyPairEmbeddedDriver: ~

    Padam87\MoneyBundle\Money\Formatter\NumberFormatterFactory: ~

    padam87_money.number_formatter:
        class: \NumberFormatter
        factory:   'Padam87\MoneyBundle\Money\Formatter\NumberFormatterFactory:createNumberFormatter'
        arguments: ['@request_stack', '%locale%']

    Money\Formatter\IntlMoneyFormatter:
        arguments:
            - '@padam87_money.number_formatter'
            - '@Money\Currencies\CurrencyList'

    Padam87\MoneyBundle\Service\MoneyHelper:
        public: true
        arguments:
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Form\MoneyType:
        arguments:
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Form\CurrencyType:
        arguments:
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Exchange\DatabaseExchange:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'

    Money\Exchange\ReversedCurrenciesExchange:
        arguments:
            - '@Padam87\MoneyBundle\Exchange\DatabaseExchange'

    Money\Converter:
        class: Money\Converter
        arguments:
            - '@Money\Currencies\CurrencyList'
            - '@Money\Exchange\ReversedCurrenciesExchange'
