services:
    _defaults:
        public: false

    Padam87\MoneyBundle\Doctrine\Mapping\Driver\MoneyEmbeddedDriver:
        arguments:
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Service\MoneyFormatter:
        arguments:
            $requestStack: '@request_stack'
            $defaultLocale: '%kernel.default_locale%'
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Form\CurrencyType:
        arguments:
            $config: '%padam87_money.config%'
        tags:
            - 'form.type'

    Padam87\MoneyBundle\Form\DecimalType:
        tags:
            - 'form.type'

    Padam87\MoneyBundle\Form\MoneyType:
        tags:
            - 'form.type'

    Padam87\MoneyBundle\Twig\Extension\MoneyExtension:
        arguments:
            $formatter: '@Padam87\MoneyBundle\Service\MoneyFormatter'
            $converter: '@Brick\Money\CurrencyConverter'
        tags:
            - 'twig.extension'

    Padam87\MoneyBundle\Service\DatabaseExchangeRateProvider:
        arguments:
            $doctrine: '@doctrine'

    Brick\Money\CurrencyConverter:
        arguments:
            $exchangeRateProvider: '@Padam87\MoneyBundle\Service\DatabaseExchangeRateProvider'
