services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Padam87\MoneyBundle\Doctrine\Mapping\Driver\MoneyEmbeddedDriver:
        arguments:
            $config: '%padam87_money.config%'

    Padam87\MoneyBundle\Money\Formatter\NumberFormatterFactory: ~

    padam87_money.number_formatter:
        class: \NumberFormatter
        factory:   'Padam87\MoneyBundle\Money\Formatter\NumberFormatterFactory:createNumberFormatter'
        arguments: ['@request_stack', '%locale%']

    Money\Formatter\IntlMoneyFormatter:
        arguments:
            - '@padam87_money.number_formatter'
            - '@Money\Currencies\CurrencyList'

    Padam87\MoneyBundle\Service\MoneyHelper:
        public: true
        arguments:
            - '%padam87_money.config%'

    Padam87\MoneyBundle\Form\MoneyType: ~
    Padam87\MoneyBundle\Form\CurrencyType:
        arguments:
            - '%padam87_money.config%'
